# Generated by Django 4.2.11 on 2025-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.BigIntegerField(blank=True, default=None, null=True)),
                ('patient', models.BigIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('pill', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_daily', models.BooleanField(default=False)),
                ('is_medication_taken', models.BooleanField(default=False)),
                ('set_date', models.DateField(blank=True, default=None, null=True)),
                ('set_time', models.TimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
