# Generated by Django 4.2.11 on 2025-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='face',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='nurse_faces'),
        ),
        migrations.AddField(
            model_name='patient',
            name='face',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='patient_faces'),
        ),
    ]
