# Generated by Django 4.2.11 on 2025-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='account_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='account_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='account_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
    ]
