# Generated by Django 4.2.11 on 2025-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_nurse_account_id_alter_patient_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='account_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
