# Generated by Django 4.2.11 on 2025-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_schedule_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
