# Generated by Django 4.2.18 on 2025-01-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_account_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
