# Generated by Django 4.2.18 on 2025-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_lockinglogs_alter_nurse_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockinglogs',
            name='is_for_locking',
            field=models.BooleanField(default=True),
        ),
    ]
